Re-former project following the Odin Project Instructions
jadx2/re-former pull request #1
Opened 2021-02-15 22:36 UTC by jadx2

We created a model for the users with its corresponding controller to create and edit.
Also, the views to interact with the database from the browser.

2021-02-15 23:13 UTC, blackpintz requested changes
# Status: Changes Required 🛑

### Hello team 👋,

**Great job on your project 👏.**

### Highlights

- **Your README is professional.**
- **You have passed most of the requirements.**

### Mandatory Requirements

- **Please check the comments below.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

2021-02-15 23:13 UTC, blackpintz commented on config/routes.rb
>    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Use the `:only` option to specify only the routes used in this application. See screenshot [one](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png) and [two](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) of this requirement.

2021-02-15 23:13 UTC, blackpintz commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Remove the commented code.

2021-02-15 23:13 UTC, blackpintz commented on app/views/users/new.html.erb
> +  <%= email_field(:user, :email) %>
Write `email_field_tag` properly.

2021-02-16 15:07 UTC, elmejdki commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
remove the commented code in the users_controller

2021-02-16 15:07 UTC, elmejdki commented on app/views/users/new.html.erb
> +  <%= email_field(:user, :email) %>
add _tag to the email_field in the new.html.erb

2021-02-16 15:10 UTC, elmejdki requested changes
# status: require changes :recycle: 

I think the requirements were really clear by the previous TSE, please revert your changes to the new.html.erb file and work on the comments that I have added to the previous review.
:point_up: :point_up: :point_up: :point_up: :point_up:

### Please make all the required changes, before you submit another code review.
## Happy Coding :tophat:

2021-02-16 15:57 UTC, LamiaSristy approved these changes
# Status: Approved. 🎉 🎉

Hello @jadx2 and @RokoVarano. 

**To get professionalism sometimes people need to work hard. Thank you for making the changes the former reviewers asked for.**

**After all the changes and your hard work now you have a really great project, congratulations on that.**

You can merge the branch now.

good luck with your next Project 🚀.

Feel free to reach me on slack @lamiasristy 🙋

Keep up the spirit always. 

Happy Coding 💻

2021-05-07 20:37 UTC, merged